# Generated by Django 6.0.6 on 2026-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='professional', max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbs/')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('layout_data', models.JSONField(default=dict)),
                ('default_colors', models.JSONField(default=list)),
                ('default_fonts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📄', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
            },
        ),
    ]
